import type { Metadata } from "next";
import "./globals.css";
import { lora } from '../ui/fonts';

export const metadata: Metadata = {
  title: "Dictionary web app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
    >
      <body className={`${lora.className} min-h-full flex flex-col`}>{children}</body>
    </html>
  );
}
